services:
  postgres:
    image: postgres:18
    container_name: pg-cidadaomais
    restart: always
    ports:
      - "5433:5432"
    shm_size: 2gb
    
    environment:
      - PGDATA=/var/lib/postgresql/18/data
    env_file:
      - .env
    volumes:
      - ./postgres/data:/var/lib/postgresql/18/data
      - ./postgres/backup:/var/lib/postgresql/18/backup

    command: >
      postgres
      -c shared_buffers=1536MB
      -c work_mem=4MB
      -c effective_cache_size=5GB
      -c random_page_cost=1.1